name: Workflow

on:
  push:
    branches:
      - main

jobs:
  Job:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_REPOSITORY_OWNER}"
          git config user.email "${GITHUB_REPOSITORY_OWNER}@users.noreply.github.com"
      - name: Fetch History
        run: git fetch --prune --unshallow

      - uses: FranzDiebold/github-env-vars-action@v2
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.changelog.outputs.tag }}

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
        if: ${{ steps.changelog.outputs.tag }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.CI_REPOSITORY_OWNER_SLUG }}/${{ env.CI_REPOSITORY_NAME_SLUG }}:${{ env.CI_SHA_SHORT }}
            ghcr.io/${{ env.CI_REPOSITORY_OWNER_SLUG }}/${{ env.CI_REPOSITORY_NAME_SLUG }}:latest
        if: ${{ steps.changelog.outputs.tag }}          
          
